pipeline {
    agent any

    environment {
        GIT_CREDENTIALS_ID = 'github-pat' // The ID of your PAT in Jenkins credentials
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout GitHub repo using PAT
                git branch: 'master',
                    url: 'https://github.com/k-patidar/publicholliday-calander.git',
                    credentialsId: "${GIT_CREDENTIALS_ID}"
            }
        }

        stage('Build') {
            steps {
                echo 'Build stage placeholder'
                // You can add your build commands here, e.g., docker build
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}

